import { build } from 'esbuild';
import { execSync } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';

async function ensureDir(dirPath) {
  await fs.mkdir(dirPath, { recursive: true });
}

async function copyFile(src, dst) {
  await ensureDir(path.dirname(dst));
  await fs.copyFile(src, dst);
}

async function main() {
  const root = process.cwd();
  const distDir = path.join(root, 'dist');

  await fs.rm(distDir, { recursive: true, force: true });

  // Compile Tailwind CSS
  execSync(
    'npx tailwindcss -i src/renderer/input.css -o dist/renderer/styles.css --minify',
    { cwd: root, stdio: 'inherit' }
  );

  // Main process
  await build({
    entryPoints: [path.join(root, 'src/main/main.ts')],
    outfile: path.join(distDir, 'main/main.js'),
    bundle: true,
    platform: 'node',
    format: 'cjs',
    target: ['node20'],
    sourcemap: true,
    external: ['electron', 'electron-log', 'ffmpeg-static', 'ffprobe-static']
  });

  // Preload
  await build({
    entryPoints: [path.join(root, 'src/preload/preload.ts')],
    outfile: path.join(distDir, 'preload/preload.js'),
    bundle: true,
    platform: 'node',
    format: 'cjs',
    target: ['node20'],
    sourcemap: true,
    external: ['electron']
  });

  // Renderer
  await build({
    entryPoints: [path.join(root, 'src/renderer/renderer.ts')],
    outfile: path.join(distDir, 'renderer/renderer.js'),
    bundle: true,
    platform: 'browser',
    format: 'esm',
    target: ['es2020'],
    sourcemap: true
  });

  // Copy HTML (CSS is already generated by Tailwind)
  await copyFile(
    path.join(root, 'src/renderer/index.html'),
    path.join(distDir, 'renderer/index.html')
  );
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exitCode = 1;
});

